table Customer_Demographics
	lineageTag: d57e1007-5de0-4046-9ff3-6fb94cc31fd5

	column Customer_ID
		dataType: string
		lineageTag: 0d93038b-c825-4e11-bfad-b7b70c4bd05d
		summarizeBy: none
		sourceColumn: Customer_ID

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 1dbd29c0-5d86-49f1-8875-c93d74669e82
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 74adcf2d-b157-473d-b871-4a80233ea2c4
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column Membership_Since
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4004aba9-a3ed-4ccb-8f5a-ddc8c630664a
		summarizeBy: none
		sourceColumn: Membership_Since

		variation Variation
			isDefault
			relationship: 57fa4c1b-2fbc-4aee-81d8-b2a7fecb75a0
			defaultHierarchy: LocalDateTable_0b90e8f5-001d-4f33-b59d-61e13248ddeb.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Marital_Status
		dataType: string
		lineageTag: 1a0c35bd-cc31-4f9f-b506-5dcedfa228d9
		summarizeBy: none
		sourceColumn: Marital_Status

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: f339e7b0-98fa-4f24-b08f-9b2172360f4b
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Income_Group
		dataType: string
		lineageTag: 5bd10654-1e29-46f0-a789-f0eb6c10f01f
		summarizeBy: none
		sourceColumn: Income_Group

		annotation SummarizationSetBy = Automatic

	column Membership_Duration = DATEDIFF(Customer_Demographics[Membership_Since], TODAY(), YEAR)
		dataType: int64
		formatString: 0
		lineageTag: 4d7d0da1-cc9b-4bcd-8c0f-073c3a38f6d7
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Store_Type
		dataType: string
		lineageTag: acdf3f4e-b3aa-4778-b56a-abebc3eee900
		summarizeBy: none
		sourceColumn: Store_Type

		annotation SummarizationSetBy = Automatic

	column Age_Group
		dataType: string
		lineageTag: e8775a48-c4fe-4002-ab77-f1d735f4159b
		summarizeBy: none
		sourceColumn: Age_Group
		sortByColumn: Age_Sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Age_Sort
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3d9c0f5b-8aae-4c6f-9051-b42f99121084
		summarizeBy: sum
		sourceColumn: Age_Sort

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Customer_Demographics = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\user\Downloads\Customer_Demographics.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Customer_ID", type text}, {"Gender", type text}, {"Age", Int64.Type}, {"Membership_Since", type date}, {"Marital_Status", type text}, {"Region", type text}, {"Income_Group", type text}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"Region"}, Store_Locations, {"Region"}, "Store_Locations", JoinKind.LeftOuter),
				    #"Expanded Store_Locations" = Table.ExpandTableColumn(#"Merged Queries", "Store_Locations", {"Store_Type"}, {"Store_Locations.Store_Type"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Expanded Store_Locations",null,"NA",Replacer.ReplaceValue,{"Store_Locations.Store_Type"}),
				    #"Removed Duplicates" = Table.Distinct(#"Replaced Value", {"Customer_ID"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Duplicates",{{"Store_Locations.Store_Type", "Store_Type"}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Renamed Columns", "Age_Group", each if [Age] < 25 then "Under 25" else if [Age] < 40 then "25-39" else if [Age] < 60 then "40-59" else "60 Plus"),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Conditional Column",{"Customer_ID", "Gender", "Age", "Age_Group", "Membership_Since", "Marital_Status", "Region", "Income_Group", "Store_Type"}),
				    #"Added Conditional Column1" = Table.AddColumn(#"Reordered Columns", "Age_Sort", each if [Age_Group] = "Under 25" then 1 else if [Age_Group] = "25-39" then 2 else if [Age_Group] = "40-59" then 3 else 4),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Conditional Column1",{{"Age_Sort", Int64.Type}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

